FROM node:18.13.0

WORKDIR /orchestrator-express

COPY . .

RUN npm install 

ENV NODE_ENV=production
ENV REDIS_PASSWORD=YiMyCBewb9A3YiAt5nwnrUFQIMV6Oc4r
ENV PORT=4000

EXPOSE 4000

CMD ["node", "app.js"]